export type DietaryTag = 'Halal' | 'Vegan' | 'Vegetarian' | 'Spicy' | 'Gluten-Free' | 'Signature' | 'Bestseller' | 'New' | 'Sharing'

export interface MenuItem {
  id: string          // primary key — e.g. mandi-01
  code: string        // 4-digit billing code — e.g. 1001
  name: string
  description: string
  price: number
  category: string
  tags: DietaryTag[]
  emoji: string
  available: boolean
  isVeg: boolean
  spiceLevel?: 1 | 2 | 3   // 1 = mild, 2 = medium, 3 = hot
  servingSize?: string
  image?: string
}

export interface MenuCategory {
  id: string
  label: string
  emoji: string
  description: string
}

export const categories: MenuCategory[] = [
  { id: 'all',       label: 'All Items',         emoji: '🌟', description: 'Our complete menu' },
  { id: 'mandi',     label: 'Mandi',             emoji: '🍖', description: 'Our signature slow-smoked Mandi dishes' },
  { id: 'grills',    label: 'Grills & Kebabs',   emoji: '🔥', description: 'Charcoal-grilled meats and skewers' },
  { id: 'rice',      label: 'Rice Dishes',       emoji: '🍚', description: 'Aromatic rice preparations' },
  { id: 'mezze',     label: 'Mezze & Starters',  emoji: '🥗', description: 'Traditional Arabic starters and dips' },
  { id: 'breads',    label: 'Breads & Sides',    emoji: '🫓', description: 'Fresh-baked breads and accompaniments' },
  { id: 'desserts',  label: 'Desserts',          emoji: '🍮', description: 'Traditional Arabian sweets' },
  { id: 'beverages', label: 'Beverages',         emoji: '🥤', description: 'Fresh juices, teas, and cooling drinks' },
]

export const menuItems: MenuItem[] = [
  // ─── MANDI ────────────────────────────────────────────────────────────────
  {
    id: 'mandi-01',
    code: '1001',
    name: 'Lamb Mandi (Full)',
    description: 'A whole slow-smoked lamb leg placed over fragrant saffron basmati rice, cooked in our traditional underground tandoor for 6 hours. Served with Sahawiq (green chili sauce) and Zabadi (yoghurt).',
    price: 1200,
    category: 'mandi',
    tags: ['Signature', 'Halal', 'Sharing'],
    emoji: '🍖',
    available: true,
    isVeg: false,
    servingSize: 'Serves 4–5',
    image: '/images/lamb-mandi.jpeg',
  },
  {
    id: 'mandi-02',
    code: '1002',
    name: 'Lamb Mandi (Half)',
    description: 'Half portion of our signature slow-smoked lamb Mandi. Tender, smoky, and perfectly spiced. Served with saffron rice, Sahawiq, and Zabadi.',
    price: 650,
    category: 'mandi',
    tags: ['Signature', 'Halal'],
    emoji: '🍖',
    available: true,
    isVeg: false,
    servingSize: 'Serves 2',
    image: '/images/lamb-mandi-half.jpeg',
  },
  {
    id: 'mandi-03',
    code: '1003',
    name: 'Chicken Mandi (Full)',
    description: 'Whole chicken marinated in traditional Yemeni Hawaij spice blend, slow-smoked over aromatic wood and basmati rice. Incredibly tender with golden, crispy skin.',
    price: 780,
    category: 'mandi',
    tags: ['Bestseller', 'Halal', 'Sharing'],
    emoji: '🍗',
    available: true,
    isVeg: false,
    servingSize: 'Serves 3–4',
    image: '/images/Create_images_of_Mandi_biriyani,_202605151901.jpeg',
  },
  {
    id: 'mandi-04',
    code: '1004',
    name: 'Chicken Mandi (Half)',
    description: 'Half portion of our beloved chicken Mandi — smoky, juicy, and served over saffron basmati rice. Comes with Sahawiq and cooling yoghurt.',
    price: 420,
    category: 'mandi',
    tags: ['Bestseller', 'Halal'],
    emoji: '🍗',
    available: true,
    isVeg: false,
    servingSize: 'Serves 1–2',
    image: '/images/chicken-mandi.jpeg',
  },
  {
    id: 'mandi-05',
    code: '1005',
    name: 'Prawn Mandi',
    description: 'Jumbo prawns marinated in Arabian spices and slow-cooked over fragrant saffron rice. A coastal twist on our Yemeni classic. Seasonal availability.',
    price: 880,
    category: 'mandi',
    tags: ['New', 'Halal', 'Signature'],
    emoji: '🦐',
    available: true,
    isVeg: false,
    servingSize: 'Serves 2',
    image: '/images/Create_images_of_Mandi_biriyani,_202605151907-2.jpeg',
  },

  // ─── GRILLS ────────────────────────────────────────────────────────────────
  {
    id: 'grill-01',
    code: '2001',
    name: 'Mixed Grill Platter',
    description: 'A grand platter of Shish Tawook (chicken skewers), Kafta (spiced minced lamb), Lamb Chops, and Seekh Kebab. Served with garlic sauce, pickles, and Arabic bread.',
    price: 680,
    category: 'grills',
    tags: ['Signature', 'Halal', 'Sharing'],
    emoji: '🍢',
    available: true,
    isVeg: false,
    servingSize: 'Serves 2–3',
    image: '/images/mixed-grill-platter.jpeg',
  },
  {
    id: 'grill-02',
    code: '2002',
    name: 'Shish Tawook',
    description: 'Tender chunks of chicken marinated in Lebanese-style yoghurt, garlic, and lemon, grilled on charcoal skewers. Served with toum (garlic sauce) and pita.',
    price: 320,
    category: 'grills',
    tags: ['Halal', 'Bestseller'],
    emoji: '🍡',
    available: true,
    isVeg: false,
    image: '/images/shish-tawook.jpeg',
  },
  {
    id: 'grill-03',
    code: '2003',
    name: 'Lamb Kafta',
    description: 'Hand-rolled minced lamb mixed with parsley, onion, and Arabian spices, charcoal-grilled and served with tahini and a side salad.',
    price: 360,
    category: 'grills',
    tags: ['Halal', 'Spicy'],
    emoji: '🍢',
    available: true,
    isVeg: false,
    spiceLevel: 2,
    image: '/images/lamb-kafta.jpeg',
  },
  {
    id: 'grill-04',
    code: '2004',
    name: 'Grilled Lamb Chops',
    description: 'Four succulent lamb chops marinated in a blend of Arabic seven-spice, rosemary, and garlic. Grilled to perfection. Served with mint yoghurt and fattoush.',
    price: 520,
    category: 'grills',
    tags: ['Signature', 'Halal'],
    emoji: '🥩',
    available: true,
    isVeg: false,
    image: '/images/lamb-chops.jpeg',
  },
  {
    id: 'grill-05',
    code: '2005',
    name: 'Beef Shawarma Platter',
    description: 'Freshly sliced marinated beef shawarma served with garlic sauce, pickles, sliced tomato, and crispy fries. Accompanied by warm Arabic bread.',
    price: 280,
    category: 'grills',
    tags: ['Bestseller', 'Halal'],
    emoji: '🌯',
    available: true,
    isVeg: false,
    image: '/images/beef-shawarma.jpeg',
  },
  {
    id: 'grill-06',
    code: '2006',
    name: 'Chicken Shawarma Platter',
    description: 'Tender spiced chicken shawarma with toum, pickled vegetables, and fries. A street-food classic elevated to restaurant quality.',
    price: 240,
    category: 'grills',
    tags: ['Bestseller', 'Halal'],
    emoji: '🌯',
    available: true,
    isVeg: false,
    image: '/images/Macro_style_Professional_food_photography_202605151913.jpeg',
  },

  // ─── RICE DISHES ───────────────────────────────────────────────────────────
  {
    id: 'rice-01',
    code: '3001',
    name: 'Mutton Kabsa',
    description: 'Saudi Arabia\'s national dish. Slow-cooked mutton in a rich tomato-and-spice broth over fragrant basmati rice with dried fruits, nuts, and a 12-spice blend.',
    price: 480,
    category: 'rice',
    tags: ['Signature', 'Halal'],
    emoji: '🍛',
    available: true,
    isVeg: false,
    spiceLevel: 1,
    image: '/images/Create_images_of_Mandi_biriyani,_202605151907.jpeg',
  },
  {
    id: 'rice-02',
    code: '3002',
    name: 'Chicken Biryani (Arabic Style)',
    description: 'Arabic-style layered biryani with saffron, rose water, caramelised onions, dried apricots, and almonds. Lighter and more fragrant than its Indian counterpart.',
    price: 340,
    category: 'rice',
    tags: ['Halal', 'Bestseller'],
    emoji: '🍚',
    available: true,
    isVeg: false,
    spiceLevel: 1,
    image: '/images/Create_image_of_Mandi_biriyani,_202605151903.jpeg',
  },
  {
    id: 'rice-03',
    code: '3003',
    name: 'Machboos (Fish & Rice)',
    description: 'Bahraini-style spiced fish over rice cooked in a tomato, onion, and loomi (dried lime) broth. Made with fresh catch of the day.',
    price: 420,
    category: 'rice',
    tags: ['Halal', 'New'],
    emoji: '🐟',
    available: true,
    isVeg: false,
    spiceLevel: 2,
    image: '/images/machboos.jpeg',
  },
  {
    id: 'rice-04',
    code: '3004',
    name: 'Sayadieh',
    description: 'Lebanese fisherman\'s rice — caramelised onions and spiced rice topped with crispy fried fish. Served with tahini sauce and lemon.',
    price: 390,
    category: 'rice',
    tags: ['Halal', 'Signature'],
    emoji: '🍚',
    available: true,
    isVeg: false,
    image: '/images/sayadieh.jpeg',
  },

  // ─── MEZZE & STARTERS ──────────────────────────────────────────────────────
  {
    id: 'mezze-01',
    code: '4001',
    name: 'Grand Mezze Platter',
    description: 'A feast of Hummus, Mutabbal (smoky aubergine dip), Fattoush salad, Tabbouleh, Labneh, olives, and pickles. Served with a basket of warm pita bread.',
    price: 380,
    category: 'mezze',
    tags: ['Vegan', 'Sharing', 'Signature'],
    emoji: '🥗',
    available: true,
    isVeg: true,
    servingSize: 'Serves 3–4',
    image: '/images/Macro_style_Professional_food_photography_202605151911-2.jpeg',
  },
  {
    id: 'mezze-02',
    code: '4002',
    name: 'Classic Hummus',
    description: 'Stone-ground chickpeas blended with premium tahini, fresh lemon, and garlic. Drizzled with extra-virgin olive oil and dusted with paprika. Served with warm pita.',
    price: 140,
    category: 'mezze',
    tags: ['Vegan', 'Gluten-Free'],
    emoji: '🫘',
    available: true,
    isVeg: true,
    image: '/images/Macro_style_Professional_food_photography_202605151909-2.jpeg',
  },
  {
    id: 'mezze-03',
    code: '4003',
    name: 'Mutabbal (Baba Ganoush)',
    description: 'Charcoal-roasted aubergine blended with tahini, garlic, lemon, and pomegranate molasses. Topped with pomegranate seeds and fresh mint.',
    price: 160,
    category: 'mezze',
    tags: ['Vegan', 'Gluten-Free'],
    emoji: '🍆',
    available: true,
    isVeg: true,
    image: '/images/mutabbal.jpeg',
  },
  {
    id: 'mezze-04',
    code: '4004',
    name: 'Fattoush Salad',
    description: 'Fresh romaine, tomatoes, cucumber, radish, and mint tossed in a sumac-pomegranate dressing, topped with crispy fried pita chips.',
    price: 160,
    category: 'mezze',
    tags: ['Vegan', 'Vegetarian'],
    emoji: '🥗',
    available: true,
    isVeg: true,
    image: '/images/fattoush.jpeg',
  },
  {
    id: 'mezze-05',
    code: '4005',
    name: 'Tabbouleh',
    description: 'Finely chopped fresh parsley, mint, tomato, and spring onion, dressed with lemon juice and olive oil. A Lebanese classic done right.',
    price: 150,
    category: 'mezze',
    tags: ['Vegan', 'Gluten-Free'],
    emoji: '🌿',
    available: true,
    isVeg: true,
    image: '/images/tabbouleh.jpeg',
  },
  {
    id: 'mezze-06',
    code: '4006',
    name: 'Falafel Plate',
    description: 'Six golden crispy falafel balls made from freshly soaked chickpeas and herbs, served with tahini dip, pickles, and pita bread.',
    price: 180,
    category: 'mezze',
    tags: ['Vegan', 'Vegetarian'],
    emoji: '🟢',
    available: true,
    isVeg: true,
    image: '/images/Macro_style_Professional_food_photography_202605151909-3.jpeg',
  },
  {
    id: 'mezze-07',
    code: '4007',
    name: 'Stuffed Grape Leaves (Warak Dawali)',
    description: 'Hand-rolled vine leaves stuffed with herbed rice, tomato, and lemon. Cooked until tender and served with yoghurt and lemon wedges.',
    price: 200,
    category: 'mezze',
    tags: ['Vegan', 'Vegetarian', 'Signature'],
    emoji: '🌿',
    available: true,
    isVeg: true,
    image: '/images/grape-leaves.jpeg',
  },
  {
    id: 'mezze-08',
    code: '4008',
    name: 'Harissa Soup',
    description: 'A hearty slow-cooked wheat and shredded chicken soup, seasoned with cumin and finished with ghee. Warming and deeply nourishing.',
    price: 180,
    category: 'mezze',
    tags: ['Halal', 'New'],
    emoji: '🍲',
    available: true,
    isVeg: false,
    spiceLevel: 1,
    image: '/images/harissa-soup.jpeg',
  },

  // ─── BREADS & SIDES ────────────────────────────────────────────────────────
  {
    id: 'bread-01',
    code: '5001',
    name: 'Tandoor Khubz (Arabic Bread)',
    description: 'Freshly baked soft Arabic flatbread from our clay tandoor. Comes in pairs. The perfect companion to any Mezze or dip.',
    price: 60,
    category: 'breads',
    tags: ['Vegan', 'Vegetarian'],
    emoji: '🫓',
    available: true,
    isVeg: true,
    servingSize: '2 pieces',
    image: '/images/arabic-bread.jpeg',
  },
  {
    id: 'bread-02',
    code: '5002',
    name: 'Cheese Manakish',
    description: 'Arabic flatbread topped with a blend of Akkawi and mozzarella cheeses, baked until golden and bubbly in our wood-fired oven.',
    price: 160,
    category: 'breads',
    tags: ['Vegetarian'],
    emoji: '🧀',
    available: true,
    isVeg: true,
    image: '/images/cheese-manakish.jpeg',
  },
  {
    id: 'bread-03',
    code: '5003',
    name: 'Za\'atar Manakish',
    description: 'Thin Arabic flatbread generously spread with a blend of za\'atar (wild thyme), sumac, sesame, and premium olive oil. Baked until crisp.',
    price: 120,
    category: 'breads',
    tags: ['Vegan', 'Vegetarian', 'Bestseller'],
    emoji: '🌿',
    available: true,
    isVeg: true,
    image: '/images/zaatar-manakish.jpeg',
  },
  {
    id: 'bread-04',
    code: '5004',
    name: 'Saffron Rice (Side)',
    description: 'A generous portion of our signature saffron-infused basmati rice, cooked with whole spices, caramelised onions, and a touch of rose water.',
    price: 120,
    category: 'breads',
    tags: ['Vegan', 'Gluten-Free'],
    emoji: '🍚',
    available: true,
    isVeg: true,
    servingSize: 'Single portion',
    image: '/images/saffron-rice.jpeg',
  },
  {
    id: 'bread-05',
    code: '5005',
    name: 'Crispy Fries',
    description: 'Double-fried golden potato fries seasoned with our house Arabic spice mix. Served with garlic aioli and tomato sauce.',
    price: 100,
    category: 'breads',
    tags: ['Vegan', 'Vegetarian'],
    emoji: '🍟',
    available: true,
    isVeg: true,
    image: '/images/crispy-fries.jpeg',
  },

  // ─── DESSERTS ──────────────────────────────────────────────────────────────
  {
    id: 'dessert-01',
    code: '6001',
    name: 'Umm Ali',
    description: 'Egypt\'s beloved warm bread pudding — layers of crispy puff pastry soaked in cream and milk, baked with coconut, raisins, and pistachios until golden. A timeless Arabic dessert.',
    price: 180,
    category: 'desserts',
    tags: ['Vegetarian', 'Signature', 'Bestseller'],
    emoji: '🍮',
    available: true,
    isVeg: true,
    image: '/images/umm-ali.jpeg',
  },
  {
    id: 'dessert-02',
    code: '6002',
    name: 'Kunafa',
    description: 'Classic Palestinian Kunafa — shredded wheat pastry filled with stretchy Akkawi cheese, soaked in orange blossom sugar syrup, and garnished with crushed pistachios. Served warm.',
    price: 200,
    category: 'desserts',
    tags: ['Vegetarian', 'Signature'],
    emoji: '🥮',
    available: true,
    isVeg: true,
    image: '/images/kunafa.jpeg',
  },
  {
    id: 'dessert-03',
    code: '6003',
    name: 'Baklava (6 pcs)',
    description: 'Six pieces of golden layered phyllo pastry filled with a blend of walnuts and pistachios, soaked in honey and rose water syrup.',
    price: 160,
    category: 'desserts',
    tags: ['Vegetarian'],
    emoji: '🍯',
    available: true,
    isVeg: true,
    servingSize: '6 pieces',
    image: '/images/baklava.jpeg',
  },
  {
    id: 'dessert-04',
    code: '6004',
    name: 'Basbousa (Semolina Cake)',
    description: 'Traditional Egyptian semolina and coconut cake soaked in rose water syrup and topped with an almond. Light, moist, and irresistibly fragrant.',
    price: 140,
    category: 'desserts',
    tags: ['Vegetarian'],
    emoji: '🍰',
    available: true,
    isVeg: true,
    image: '/images/basbousa.jpeg',
  },
  {
    id: 'dessert-05',
    code: '6005',
    name: 'Dates & Cream',
    description: 'Medjool dates stuffed with almond cream and served with a drizzle of honey and crushed pistachio. A light and regal end to your meal.',
    price: 120,
    category: 'desserts',
    tags: ['Vegetarian', 'Gluten-Free', 'New'],
    emoji: '🌴',
    available: true,
    isVeg: true,
    image: '/images/dates-cream.jpeg',
  },

  // ─── BEVERAGES ─────────────────────────────────────────────────────────────
  {
    id: 'bev-01',
    code: '7001',
    name: 'Arabic Qahwa (Coffee)',
    description: 'Traditional Arabian green coffee brewed with saffron, cardamom, and cloves. Served in a dallah (Arabic coffee pot) with dates. The essence of Arabian hospitality.',
    price: 100,
    category: 'beverages',
    tags: ['Vegan', 'Signature'],
    emoji: '☕',
    available: true,
    isVeg: true,
    servingSize: 'Pot — 2–3 cups',
    image: '/images/arabic-coffee.jpeg',
  },
  {
    id: 'bev-02',
    code: '7002',
    name: 'Mint Lemonade',
    description: 'Freshly squeezed lemons blended with crushed mint, sugar, and ice. Bright, refreshing, and the perfect companion for a Mandi feast.',
    price: 80,
    category: 'beverages',
    tags: ['Vegan', 'Bestseller'],
    emoji: '🍋',
    available: true,
    isVeg: true,
    image: '/images/mint-lemonade.jpeg',
  },
  {
    id: 'bev-03',
    code: '7003',
    name: 'Rose Water Lemonade',
    description: 'A floral twist on classic lemonade — fresh lemon juice with rose water, a pinch of saffron, and crushed ice. Delicate and fragrant.',
    price: 90,
    category: 'beverages',
    tags: ['Vegan', 'Signature'],
    emoji: '🌹',
    available: true,
    isVeg: true,
    image: '/images/rose-lemonade.jpeg',
  },
  {
    id: 'bev-04',
    code: '7004',
    name: 'Mango Lassi',
    description: 'Thick Alphonso mango blended with chilled yoghurt and a whisper of cardamom. Cooling and indulgent.',
    price: 100,
    category: 'beverages',
    tags: ['Vegetarian', 'Bestseller'],
    emoji: '🥭',
    available: true,
    isVeg: true,
    image: '/images/mango-lassi.jpeg',
  },
  {
    id: 'bev-05',
    code: '7005',
    name: 'Jallab Juice',
    description: 'A classic Levantine drink made from grape juice, rose water, and pomegranate molasses, served over ice with raisins and pine nuts.',
    price: 110,
    category: 'beverages',
    tags: ['Vegan', 'New'],
    emoji: '🍇',
    available: true,
    isVeg: true,
    image: '/images/jallab-juice.jpeg',
  },
  {
    id: 'bev-06',
    code: '7006',
    name: 'Karak Chai',
    description: 'Strong milk tea brewed with cardamom, saffron, and cinnamon — the Gulf\'s answer to chai. Rich, warming, and deeply aromatic.',
    price: 70,
    category: 'beverages',
    tags: ['Vegetarian', 'Bestseller'],
    emoji: '🍵',
    available: true,
    isVeg: true,
    image: '/images/karak-chai.jpeg',
  },
  {
    id: 'bev-07',
    code: '7007',
    name: 'Fresh Watermelon Juice',
    description: 'Cold-pressed fresh watermelon juice with a squeeze of lime. Pure, simple, and utterly refreshing.',
    price: 80,
    category: 'beverages',
    tags: ['Vegan'],
    emoji: '🍉',
    available: true,
    isVeg: true,
    image: '/images/watermelon-juice.jpeg',
  },
]

export const tagColors: Record<string, { bg: string; color: string }> = {
  Signature:    { bg: 'rgba(200,150,12,0.18)',  color: '#E8B84B' },
  Bestseller:   { bg: 'rgba(212,112,10,0.18)',  color: '#F08020' },
  New:          { bg: 'rgba(30,150,80,0.18)',   color: '#5eebb0' },
  Halal:        { bg: 'rgba(139,26,42,0.22)',   color: '#e08090' },
  Vegan:        { bg: 'rgba(40,140,60,0.18)',   color: '#7ec87e' },
  Vegetarian:   { bg: 'rgba(80,160,40,0.15)',   color: '#a0d080' },
  Spicy:        { bg: 'rgba(200,50,10,0.18)',   color: '#f08060' },
  'Gluten-Free':{ bg: 'rgba(100,80,200,0.15)',  color: '#b0a0f0' },
  Sharing:      { bg: 'rgba(80,80,160,0.18)',   color: '#a0a0e8' },
}
